/* ------------------------------------------------------------------ *
 * The industry cue files, one per trade (generated by the audio
 * pipeline's split_industry_cues.py: do not edit by hand).
 *
 * Loaded only through lib/audio's loadIndustryCueFile, itself an
 * import() of this module once sound is on, so neither this map nor any
 * cue is in a page's first load, and a trade page fetches its own
 * trade's file and no other.
 * ------------------------------------------------------------------ */

import type { IndustrySurface } from "./index";

type Loader = () => Promise<{ default: unknown }>;

export const INDUSTRY_CUES: Record<IndustrySurface, Record<string, Loader>> = {
  "industry-first-question": {
    automotive: () => import("./cues/industry/first-question/automotive.json"),
    "clinics-dental": () => import("./cues/industry/first-question/clinics-dental.json"),
    education: () => import("./cues/industry/first-question/education.json"),
    "financial-services": () => import("./cues/industry/first-question/financial-services.json"),
    fitness: () => import("./cues/industry/first-question/fitness.json"),
    "home-services": () => import("./cues/industry/first-question/home-services.json"),
    hospitality: () => import("./cues/industry/first-question/hospitality.json"),
    insurance: () => import("./cues/industry/first-question/insurance.json"),
    "law-firms": () => import("./cues/industry/first-question/law-firms.json"),
    logistics: () => import("./cues/industry/first-question/logistics.json"),
    "property-management": () => import("./cues/industry/first-question/property-management.json"),
    "real-estate": () => import("./cues/industry/first-question/real-estate.json"),
    restaurants: () => import("./cues/industry/first-question/restaurants.json"),
    retail: () => import("./cues/industry/first-question/retail.json"),
    "salons-spas": () => import("./cues/industry/first-question/salons-spas.json"),
    veterinary: () => import("./cues/industry/first-question/veterinary.json"),
  },
  "industry-run-it-call": {
    automotive: () => import("./cues/industry/run-it-call/automotive.json"),
    "clinics-dental": () => import("./cues/industry/run-it-call/clinics-dental.json"),
    education: () => import("./cues/industry/run-it-call/education.json"),
    "financial-services": () => import("./cues/industry/run-it-call/financial-services.json"),
    fitness: () => import("./cues/industry/run-it-call/fitness.json"),
    "home-services": () => import("./cues/industry/run-it-call/home-services.json"),
    hospitality: () => import("./cues/industry/run-it-call/hospitality.json"),
    insurance: () => import("./cues/industry/run-it-call/insurance.json"),
    "law-firms": () => import("./cues/industry/run-it-call/law-firms.json"),
    logistics: () => import("./cues/industry/run-it-call/logistics.json"),
    "property-management": () => import("./cues/industry/run-it-call/property-management.json"),
    "real-estate": () => import("./cues/industry/run-it-call/real-estate.json"),
    restaurants: () => import("./cues/industry/run-it-call/restaurants.json"),
    retail: () => import("./cues/industry/run-it-call/retail.json"),
    "salons-spas": () => import("./cues/industry/run-it-call/salons-spas.json"),
    veterinary: () => import("./cues/industry/run-it-call/veterinary.json"),
  },
  "industry-wall-retraction": {
    automotive: () => import("./cues/industry/wall-retraction/automotive.json"),
    "clinics-dental": () => import("./cues/industry/wall-retraction/clinics-dental.json"),
    education: () => import("./cues/industry/wall-retraction/education.json"),
    "financial-services": () => import("./cues/industry/wall-retraction/financial-services.json"),
    fitness: () => import("./cues/industry/wall-retraction/fitness.json"),
    "home-services": () => import("./cues/industry/wall-retraction/home-services.json"),
    hospitality: () => import("./cues/industry/wall-retraction/hospitality.json"),
    insurance: () => import("./cues/industry/wall-retraction/insurance.json"),
    "law-firms": () => import("./cues/industry/wall-retraction/law-firms.json"),
    logistics: () => import("./cues/industry/wall-retraction/logistics.json"),
    "property-management": () => import("./cues/industry/wall-retraction/property-management.json"),
    "real-estate": () => import("./cues/industry/wall-retraction/real-estate.json"),
    restaurants: () => import("./cues/industry/wall-retraction/restaurants.json"),
    retail: () => import("./cues/industry/wall-retraction/retail.json"),
    "salons-spas": () => import("./cues/industry/wall-retraction/salons-spas.json"),
    veterinary: () => import("./cues/industry/wall-retraction/veterinary.json"),
  },
  "industry-bench-intents": {
    automotive: () => import("./cues/industry/bench-intents/automotive.json"),
    "clinics-dental": () => import("./cues/industry/bench-intents/clinics-dental.json"),
    education: () => import("./cues/industry/bench-intents/education.json"),
    "financial-services": () => import("./cues/industry/bench-intents/financial-services.json"),
    fitness: () => import("./cues/industry/bench-intents/fitness.json"),
    "home-services": () => import("./cues/industry/bench-intents/home-services.json"),
    hospitality: () => import("./cues/industry/bench-intents/hospitality.json"),
    insurance: () => import("./cues/industry/bench-intents/insurance.json"),
    "law-firms": () => import("./cues/industry/bench-intents/law-firms.json"),
    logistics: () => import("./cues/industry/bench-intents/logistics.json"),
    "property-management": () => import("./cues/industry/bench-intents/property-management.json"),
    "real-estate": () => import("./cues/industry/bench-intents/real-estate.json"),
    restaurants: () => import("./cues/industry/bench-intents/restaurants.json"),
    retail: () => import("./cues/industry/bench-intents/retail.json"),
    "salons-spas": () => import("./cues/industry/bench-intents/salons-spas.json"),
    veterinary: () => import("./cues/industry/bench-intents/veterinary.json"),
  },
};

/** One trade's cue file of an industry surface, as its module has it; rejects for a trade it has no file for. */
export function loadIndustryCueModule(surface: IndustrySurface, slug: string) {
  const files = INDUSTRY_CUES[surface];
  if (!Object.prototype.hasOwnProperty.call(files, slug)) return Promise.reject(new Error(`${surface}/${slug}: no cue file`));
  return files[slug]();
}
